package MenuView;

import MenuUtama.MenuUtama;
import java.awt.Desktop;
import java.io.File;

import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import kelas.suratMasuk;

import MenuView.SubSuratMasuk;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author rizan
 */
public class SuratMasuk extends javax.swing.JFrame {

    String judul;

    /**
     * Creates new form SuratMasuk
     */
    public SuratMasuk() {

        initComponents();
        otoID();
     

    //    ambilDetail();

    }

    public void ambilDetail() {

//            suratMasuk sut = new suratMasuk();
        tf_id.setText(suratMasuk.getId_surat());
        tf_Judul.setText(suratMasuk.getJudul());
        tf_Perihal.setText(suratMasuk.getPerihal());
        tf_NoSurat.setText(suratMasuk.getNo_surat());
        tf_asal.setText(suratMasuk.getAsal_surat());
        tf_Tujuan.setText(suratMasuk.getTujuan());
        tf_Jenis.setText(suratMasuk.getJenis_surat());

        tTanggalDiterima.setDate(suratMasuk.getTanggal_diterima());
        tf_ket.setText(suratMasuk.getKeterangan());
        txtfilepath.setText(suratMasuk.getFile_data());

    }

    void otoID() {
        try {
            suratMasuk surat = new suratMasuk();
            String autoId = surat.otoID();

            if (autoId != null) {
                tf_id.setText(autoId);
            } else {
                tf_id.setText("1");
            }
            // tf_id.setEditable(false);
            tf_id.setEnabled(false);

        } catch (SQLException sQLException) {
            System.out.println("Error saat memperoleh ID otomatis: " + sQLException.getMessage());
            tf_id.setText("1");
        }
    }

    void reset() {
        tf_id.setText(null);
        tf_Judul.setText(null);
        tf_Perihal.setText(null);
        tf_NoSurat.setText(null);
        tf_asal.setText(null);
        tf_Perihal.setText(null);
        tf_Tujuan.setText(null);
        tTanggalDiterima.setDate(null);
        tf_Jenis.setText(null);
        tf_ket.setText(null);
        txtfilepath.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_SuratMasuk = new javax.swing.JPanel();
        bt_Batal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_Judul = new javax.swing.JTextField();
        tf_Perihal = new javax.swing.JTextField();
        tf_NoSurat = new javax.swing.JTextField();
        tf_asal = new javax.swing.JTextField();
        tf_Tujuan = new javax.swing.JTextField();
        tTanggalDiterima = new com.toedter.calendar.JDateChooser();
        tf_Jenis = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_ket = new javax.swing.JTextArea();
        txtfilepath = new javax.swing.JTextField();
        bUpload = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        bOPen = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        bClose = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_SuratMasuk.setBackground(new java.awt.Color(255, 255, 255));

        bt_Batal.setBackground(new java.awt.Color(204, 0, 0));
        bt_Batal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_Batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_Batal.setText("Batal");
        bt_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Surat Masuk");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Id Surat");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Judul");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Perihal");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("No. Surat");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Asal Surat");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tujuan");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tanggal Diterima");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Jenis Surat");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Keterangan");

        tf_ket.setColumns(20);
        tf_ket.setRows(5);
        jScrollPane1.setViewportView(tf_ket);

        bUpload.setBackground(new java.awt.Color(51, 255, 0));
        bUpload.setText("Upload");
        bUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUploadActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Upload Surat");

        bOPen.setText("Open FIle");
        bOPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOPenActionPerformed(evt);
            }
        });

        bTambah.setText("TAMBAH");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bClose.setText("CLOSE");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        bEdit.setText("SIMPAN");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel3))
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_id)
                                    .addComponent(tf_Judul)
                                    .addComponent(tf_Perihal)
                                    .addComponent(tf_NoSurat)
                                    .addComponent(tf_asal)
                                    .addComponent(tf_Tujuan)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_Jenis)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                                    .addComponent(tTanggalDiterima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(416, 416, 416))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bOPen)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(425, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(bClose)
                .addGap(35, 35, 35)
                .addComponent(bTambah)
                .addGap(18, 18, 18)
                .addComponent(bEdit)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_Judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_Perihal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_NoSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_asal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_Tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addComponent(tTanggalDiterima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_Jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtfilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUpload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOPen)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah)
                    .addComponent(bClose)
                    .addComponent(bEdit))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout pn_SuratMasukLayout = new javax.swing.GroupLayout(pn_SuratMasuk);
        pn_SuratMasuk.setLayout(pn_SuratMasukLayout);
        pn_SuratMasukLayout.setHorizontalGroup(
            pn_SuratMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SuratMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_Batal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_SuratMasukLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_SuratMasukLayout.setVerticalGroup(
            pn_SuratMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SuratMasukLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(bt_Batal)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_SuratMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_SuratMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(778, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BatalActionPerformed
        dispose();
    }//GEN-LAST:event_bt_BatalActionPerformed

    private void bUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUploadActionPerformed

        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(this);

        try {
            File selectedFile = jfc.getSelectedFile();
            if (selectedFile != null) {
                String filepath = selectedFile.getAbsolutePath();
                filepath = filepath.replace('\\', '/');

                SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmss");
                String timestamp = sdf.format(new Date());

                String justFileName = selectedFile.getName();
                String newName = timestamp + "_" + justFileName;

                String destinationPath = "./Upload/surat/";
                txtfilepath.setText(destinationPath + newName);

                File destinationDirectory = new File(destinationPath);
                if (!destinationDirectory.exists()) {
                    destinationDirectory.mkdirs();
                }

                File destinationFile = new File(destinationDirectory, newName);

                Files.copy(selectedFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING); // Menggunakan java.nio.file.Files untuk menyalin file
            } else {
                JOptionPane.showMessageDialog(null, "No file was selected");
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Failed to copy file: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
        }

    }//GEN-LAST:event_bUploadActionPerformed

    private void bOPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOPenActionPerformed
        try {
            String filePath = txtfilepath.getText().trim();
            File file = new File(filePath);

            if (file.exists()) {
                Desktop.getDesktop().open(file);
            } else {
                JOptionPane.showMessageDialog(this, "File tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bOPenActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed

        try {
            suratMasuk surat = new suratMasuk();

            String idSurat = tf_id.getText().trim();
            String judul = tf_Judul.getText().trim();
            String perihal = tf_Perihal.getText().trim();
            String noSurat = tf_NoSurat.getText().trim();
            String asalSurat = tf_asal.getText().trim();
            String tujuan = tf_Tujuan.getText().trim();
            java.util.Date tanggalDiterima = tTanggalDiterima.getDate();
            String jenisSurat = tf_Jenis.getText().trim();
            String keterangan = tf_ket.getText().trim();
            String filePath = txtfilepath.getText().trim();

            if (idSurat.isEmpty() || judul.isEmpty() || perihal.isEmpty() || noSurat.isEmpty()
                    || asalSurat.isEmpty() || tujuan.isEmpty() || tanggalDiterima == null
                    || jenisSurat.isEmpty() || keterangan.isEmpty() || filePath.isEmpty()) {

                String missingFields = "SEMUA KOLOM HARUS DI ISI\n" + "Kolom yang masih kosong: ";
                if (idSurat.isEmpty()) {
                    missingFields += "ID Surat, ";
                }
                if (judul.isEmpty()) {
                    missingFields += "Judul, ";
                }
                if (perihal.isEmpty()) {
                    missingFields += "Perihal, ";
                }
                if (noSurat.isEmpty()) {
                    missingFields += "No. Surat, ";
                }
                if (asalSurat.isEmpty()) {
                    missingFields += "Asal Surat, ";
                }
                if (tujuan.isEmpty()) {
                    missingFields += "Tujuan, ";
                }
                if (tanggalDiterima == null) {
                    missingFields += "Tanggal Diterima, ";
                }
                if (jenisSurat.isEmpty()) {
                    missingFields += "Jenis Surat, ";
                }
                if (keterangan.isEmpty()) {
                    missingFields += "Keterangan, ";
                }
                if (filePath.isEmpty()) {
                    missingFields += "File Path, ";
                }

                missingFields = missingFields.substring(0, missingFields.length() - 2);
                JOptionPane.showMessageDialog(null, missingFields);
                return;
            }

            surat.setId_surat(idSurat);
            surat.setJudul(judul);
            surat.setPerihal(perihal);
            surat.setNo_surat(noSurat);
            surat.setAsal_surat(asalSurat);
            surat.setTujuan(tujuan);
            surat.setTanggal_diterima(new java.sql.Date(tanggalDiterima.getTime()));
            surat.setJenis_surat(jenisSurat);
            surat.setKeterangan(keterangan);
            surat.setFile_data(filePath);

            surat.tambahSurat();

            otoID();

            reset();

        } catch (SQLException sQLException) {
            System.out.println("Data tidak masuk: " + sQLException.getMessage());
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data surat: " + sQLException.getMessage());
        }
        dispose();
        MenuUtama.pn_Utama.removeAll();
        MenuUtama.pn_Utama.add(new SubSuratMasuk());
        MenuUtama.pn_Utama.repaint();
        MenuUtama.pn_Utama.revalidate();

    }//GEN-LAST:event_bTambahActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        dispose();
    }//GEN-LAST:event_bCloseActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed

        try {
            suratMasuk surat = new suratMasuk();

            surat.setId_surat(tf_id.getText());
            surat.setJudul(tf_Judul.getText());
            surat.setPerihal(tf_Perihal.getText());
            surat.setNo_surat(tf_NoSurat.getText());
            surat.setAsal_surat(tf_asal.getText());
            surat.setTujuan(tf_Tujuan.getText());
            java.util.Date tanggalDiterima = tTanggalDiterima.getDate();

            if (tanggalDiterima != null) {
                java.sql.Date sqlDate = new java.sql.Date(tanggalDiterima.getTime());
                surat.setTanggal_diterima(sqlDate);
            } else {
                System.out.println("Tanggal diterima tidak boleh kosong");
            }

            surat.setJenis_surat(tf_Jenis.getText());
            surat.setKeterangan(tf_ket.getText());
            surat.setFile_data(txtfilepath.getText());

            surat.ubahSurat();

        } catch (SQLException sQLException) {
            System.out.println("Data tidak masuk");
        }

        dispose();

        SubSuratMasuk.pnMain.removeAll();
        SubSuratMasuk.pnMain.add(SubSuratMasuk.pnDetail);
        SubSuratMasuk.pnMain.repaint();
        SubSuratMasuk.pnMain.revalidate();


    }//GEN-LAST:event_bEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuratMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuratMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuratMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuratMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuratMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    public javax.swing.JButton bEdit;
    private javax.swing.JButton bOPen;
    public javax.swing.JButton bTambah;
    private javax.swing.JButton bUpload;
    private javax.swing.JButton bt_Batal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pn_SuratMasuk;
    public com.toedter.calendar.JDateChooser tTanggalDiterima;
    public javax.swing.JTextField tf_Jenis;
    public javax.swing.JTextField tf_Judul;
    public javax.swing.JTextField tf_NoSurat;
    public javax.swing.JTextField tf_Perihal;
    public javax.swing.JTextField tf_Tujuan;
    public javax.swing.JTextField tf_asal;
    public javax.swing.JTextField tf_id;
    public javax.swing.JTextArea tf_ket;
    public javax.swing.JTextField txtfilepath;
    // End of variables declaration//GEN-END:variables
}
